//File generated by vaweei CLI
import { Component, Input, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { CLINICAL_HISTORY } from 'src/app/utils/setup/routes.enum';

//SERVICE
import { BackendService } from 'src/app/services/backend.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';

//MODELS
import { Hobbies_Interest } from 'src/app/models/hobbies_interest.model';
import { MODELS } from 'src/app/utils/setup/model.setup';
import { Model } from 'src/app/models/vw-model.model';

import {SelectionModel} from '@angular/cdk/collections';
import {MatTableDataSource} from '@angular/material/table';
import { animate, state, style, transition, trigger } from '@angular/animations';

@Component({
  selector: 'app-clinical_note_by_patient-list-view',
  templateUrl: './clinical_note_by_patient-list-view.component.html',
  styleUrls: ['./clinical_note_by_patient-list-view.component.scss'],
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({height: '0px', minHeight: '0'})),
      state('expanded', style({height: '*'})),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ]),
  ],
})
export class ClinicalNoteByPatientListViewComponent implements OnInit {

  model : Model;
  isEmpty = false;

  displayedColumns = ['session_objective', 'session_approach', 'created_at'];
  expandedElement: any | null;
  dataSource = new MatTableDataSource<any>([]);


  $headerAction!: Subscription;

  private _patient_id: any[] = [];

  @Input()
  set patient_id(value: any) {
    this._patient_id = value;
    if(value){
      this.getByPatient(value)
    }
  }
  get patient_id(): any { return this._patient_id}

  constructor(
    private router : Router,
    private route: ActivatedRoute,
    private headerService : HeaderService,
    private backendService : BackendService,
    private utilService: UtilService
    ) {
      this.model = MODELS.find(model => model.name == 'clinical_note')!;
    }

  ngAfterViewInit(): void {
    this.$headerAction! = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'delete':
          this.delete();
          break;

        default:
          break;
      }
    });
  }

  ngOnInit(): void {
    this.headerService.setHeader({model: this.model, type:'list'});
    this.utilService.set({name:'clinical_note', type:'list'});
    // if(this.route.snapshot.paramMap.get('patient_id')){
    //   this.getByPatient(this.route.snapshot.paramMap.get('patient_id'));
    // }else{
    //   this.getAll();
    // }
  }

  getByPatient(patient_id:any){
    this.backendService.getOneById(CLINICAL_HISTORY.CLINICAL_NOTE_BY_PATIENT, patient_id).subscribe({
      next: (v) => {
        if(v.length > 0){
          this.isEmpty = false;
          this.dataSource.data = v;
        }else{
          this.isEmpty = true;
        }
      },
      error: (e) => console.error(e),
      complete: () => console.info('complete')
    });
  }

  viewRecord(track:any){
    this.router.navigate(['main','clinical-history','clinical_note','form',track.id]);
  }

  delete(){
    // this.hobbiesInterestService.deleteHobbiesInterests(this.selection.selected.map(function(hobbies_interest){return hobbies_interest.id})).subscribe({
    //   next: (v) => { console.log(v) },
    //   error: (e) => console.error(e),
    //   complete: () => this.getAll()
    // });
  }

}
    