//File generated by vaweei CLI
export interface CL_brief_list {
    id?: string;
    patient?: string;
    email?: string;
    therapy_objectives?: string;
    personal_characteristics?: string;
  }
        