//File generated by vaweei CLI

export interface General_patient {
    id: string;
    first_name?: string;
    last_name1: string;
    last_name2: string;
    address: string;
    age: string;
    date_of_birth: string;
    gender: string;
    birthplace: string;
    residence_location: string;
}

export interface Parental_data_family {
    name: string;
    age: string;
    kinship: string;
    education: string;
    ocupation: string;
    smoke_user: string;
    smoke_quantity: string;
    smoke_time: string;
    alcohol_user: string;
    alcohol_quantity: string;
    alcohol_time: string;
    addictions: string;
}

export interface Parental_data {
    parents_live_together: string;
    married: string;
    direct_family: string;
    mother: Parental_data_family;
    father: Parental_data_family;
}
  
export interface Prenatal_history {
    planned_pregnancy: string;
    desired_pregnancy: string;
    reason_pregnancy: string;
    gestation_time: string;
    prenatal_control: string;
    pregnancy_complications: string;
    pregnancy_complications_type: string;
    pregnancy_complications_cause: string;
    medications: string;
    childbirth_type: string;
    childbirth_location: string;
    childbirth_support: string;
    forceps: string;
    childbirth_duration: string;
    anesthesia_type: string;
    childbirth_complications: string;
    baby_weight: string;
    baby_size: string;
    premature: string;
    corrected_age: string;
    incubation_time: string;
    apgar: string;
    cry: string;
    anomalies: string;
    notes: string;
}

export interface HereditaryFamily_history {
    diabetes: string;
    diabetes_who: string;
    hypertension: string;
    hypertension_who: string;
    cancer: string;
    cancer_who: string;
    alcoholism: string;
    alcoholism_who: string;
    mental_illnesses: string;
    mental_illnesses_who: string;
    mental_illnesses_other: string;
    mental_illnesses_another_family: string;
}

export interface Personal_pathologic_antecedents {
    allergies: string;
    child_physical_problems: string;
    TCE: string;
    PC: string;
    hospitalizations: string;
    current_medications: string;
    neurological_risk_factors: string;
}

export interface Medical_history {
    id?: string;
    source_information?: string;
    reason_consultation?: string;
    medical_diagnosis?: string;
    patient?: General_patient;
    parental_data?: Parental_data;
    prenatal_history?: Prenatal_history;
    hereditary_family_history?: HereditaryFamily_history;
    personal_pathologic_antecedents?: Personal_pathologic_antecedents;
}