//File generated by vaweei CLI
export interface Patient {
    id: number,
    first_name: string;
    last_name1: string;
    last_name2: string;
    age: number;
    email: string;
    phone_number: string;
    image: string;
}