//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { ColorCircleModule } from 'ngx-color/circle';

import { NgSelectModule } from '@ng-select/ng-select';

import { ClinicalNoteFormViewComponent } from './clinical_note-form-view.component';

@NgModule({

  declarations: [
    ClinicalNoteFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    NgSelectModule,
    CommonModule
  ],

  exports: [
    ClinicalNoteFormViewComponent
  ]
})

export class ClinicalNoteFormViewModule { }        
        