//File generated by vaweei CLI
import { Component, OnInit, Output, EventEmitter, ViewChild, ElementRef, HostListener, OnDestroy, Input, AfterViewInit } from '@angular/core';
import { UntypedFormGroup, UntypedFormControl, Validators, UntypedFormBuilder } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';
import { CLINICAL_HISTORY } from 'src/app/utils/setup/routes.enum';

//SERVICES
import { BackendService } from 'src/app/services/backend.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';

//MODELS
import { MODELS } from 'src/app/utils/setup/model.setup';
import { Model } from 'src/app/models/vw-model.model';

@Component({
  selector: 'app-clinical_note-form-view',
  templateUrl: './clinical_note-form-view.component.html',
  styleUrls: ['./clinical_note-form-view.component.scss']
})
export class ClinicalNoteFormViewComponent implements OnInit, OnDestroy, AfterViewInit {

  formGroup: UntypedFormGroup;
  @Input() modalConfigParent: any;
  @Input() nameForm: String = '';

  $headerAction!: Subscription;

  patientList = [];

  model : Model;

  constructor(
    private backendService: BackendService,
    private router : Router,
    private route: ActivatedRoute,
    private headerService : HeaderService,
    private fb: UntypedFormBuilder,
    private utilService: UtilService
  ) {
    this.model = MODELS.find(model => model.name == 'clinical_note')!;
    this.formGroup = this.fb.group({
      patient_id:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      session_approach:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      clinical_progress:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      session_objective:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      state_of_mind:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      conducts_and_non_verbal_languages:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      observations:  new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
    });
  }

  ngAfterViewInit(): void {
    this.$headerAction = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'save':
          this.save();
          break;
      
        case 'cancel':
          this.cancel();
          break;

        default:
          break;
      }
    });
  }

  ngOnInit() {
    this.headerService.setHeader({model: this.model, type: 'form'});
    this.utilService.set({name:'clinical_note', type:'form'});
    this.formGroup.statusChanges
      .pipe(
        filter(() => this.formGroup.valid))
      .subscribe(() => this.onFormValid());

    this.formGroup.statusChanges
      .pipe(
        filter(() => this.formGroup.invalid))
      .subscribe(() => this.onFormInvalid());      
  }

  get form() { return this.formGroup.controls }

  ngOnDestroy() { this.$headerAction.unsubscribe(); }

  onFormValid() {
    this.headerService.sendInAction({action:'form', type: 'ready'});
  }

  onFormInvalid() {
    this.headerService.sendInAction({action:'form', type: 'not-ready'});
  }

  changeToUppercase(formName:string) {
    if(formName){
      const value = this.formGroup.get(formName)!.value;
      if (value) {
        this.formGroup.get(formName)!.setValue(value.toUpperCase());
      }
    }
  }

  save(){
    this.backendService.create(CLINICAL_HISTORY.CLINICAL_NOTE, this.formGroup.value).subscribe({
      next: (v) => { console.log(v); },
      error: (e) => console.error(e),
      complete: () => this.router.navigate(['../','main','clinical-history','clinical_note','list'])
    })
  }

  cancel(){
    this.router.navigate(['../','main','clinical-history','clinical_note','list']);
  }

  setPatient($ev:any){
    this.formGroup.get('patient_id')!.setValue($ev.id);
  }
}
    