//File generated by vaweei CLI
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { PSYCHOTHERAPY, ADMINISTRATION } from 'src/app/utils/setup/routes.enum';

//SERVICE
import { BackendService } from 'src/app/services/backend.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';

//MODELS
import { MODELS } from 'src/app/utils/setup/model.setup';
import { Model } from 'src/app/models/vw-model.model';

import {SelectionModel} from '@angular/cdk/collections';
import {MatTableDataSource} from '@angular/material/table';
import { animate, state, style, transition, trigger } from '@angular/animations';

@Component({
  selector: 'app-bayley_item-list-view',
  templateUrl: './bayley_item-list-view.component.html',
  styleUrls: ['./bayley_item-list-view.component.scss'],
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({height: '0px', minHeight: '0'})),
      state('expanded', style({height: '*'})),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ]),
  ],
})
export class BayleyItemListViewComponent implements OnInit {

  model : Model;

  generalColumns = ['stage', 'area'];
  secundaryColumns = ['item', 'materials', 'notes', 'stage'];
  expandedElement: any | null;
  dataSource = new MatTableDataSource<any>([]);
  currentData = []

  $headerAction!: Subscription;

  areas = [
    {value:"Cognitiva", label:"Cognitiva"},
    {value:"Lenguaje Expresivo", label:"Lenguaje Expresivo"},
    {value:"Lenguaje Receptivo", label:"Lenguaje Receptivo"},
    {value:"Motor Fino", label:"Motor Fino"},
    {value:"Motor Grueso", label:"Motor Grueso"}
  ]


  constructor(
    private router : Router,
    private route: ActivatedRoute,
    private headerService : HeaderService,
    private backendService : BackendService,
    private utilService: UtilService
    ) {
      this.model = MODELS.find(model => model.name == 'bayley-item')!;
    }

  ngAfterViewInit(): void {
    this.$headerAction! = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'delete':
          this.delete();
          break;
      
        default:
          break;
      }
    });
  }

  ngOnInit(): void {
    if(this.route.snapshot.paramMap.get('patient_id')){
      this.getByPatient(this.route.snapshot.paramMap.get('patient_id'));
    }else{
      this.getAll();
    }
    
    this.headerService.setHeader({model: this.model, type: 'list'});
    this.utilService.set({name:'bailey-item', type:'list'});
  }

  getAll(){
    this.backendService.getAll(ADMINISTRATION.BAYLEY_ITEM,{}).subscribe({
     next: (v) => {
      let list = this.group_by(this.merge_cols(v));
      this.dataSource.data = this.split_col_grouped(list);
      this.currentData = this.split_col_grouped(list);
      },
     error: (e) => console.error(e),
     complete: () => console.info('complete')
   });
  }

  getByPatient(patient_id:any){
    this.backendService.getOneById(PSYCHOTHERAPY.TRACKING_BY_PATIENT, patient_id).subscribe({
      next: (v) => { this.dataSource.data = v;
       },
      error: (e) => console.error(e),
      complete: () => console.info('complete')
    });
  }

  show(track:any){
    this.router.navigate(['main','psychotherapy','tracking','form',track.id]);
  }

  delete(){
    // this.hobbiesInterestService.deleteHobbiesInterests(this.selection.selected.map(function(hobbies_interest){return hobbies_interest.id})).subscribe({
    //   next: (v) => { console.log(v) },
    //   error: (e) => console.error(e),
    //   complete: () => this.getAll()
    // });
  }

  group_by(data:any){

    let grouped_list: any[] = []

    data.forEach( (opt:any) => {
      if ( grouped_list.find( (item) => {return item.field_to_group == opt.field_to_group}) == undefined) {
        grouped_list.push({
          'field_to_group': opt.field_to_group,
          'children': [opt]
        });
      }else{
        grouped_list.map(item => 
          {
            if(item.field_to_group == opt.field_to_group){
              item.children.push(opt);
              return item;
            }else{
              return item;
            }
          }  
        )
      }
    });

    return grouped_list;

  }

  merge_cols(data: any){
    let toGroup = data.map( (obj:any) => ({...obj, field_to_group: obj.area + "-" + obj.stage}) )
    return toGroup
  }

  split_col_grouped(data: any){
    let toGroup = data.map( (obj:any) => ({...obj, area: obj.field_to_group.split("-")[0], stage: obj.field_to_group.split("-")[1]}) )
    return toGroup
  }

  filterTableData(event: any){
    this.dataSource.data = this.currentData.filter( (obj:any) => obj.area == event.value)
  }
}
    