//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { ColorCircleModule } from 'ngx-color/circle';

import { NgSelectModule } from '@ng-select/ng-select';

import { TrackingFormDashboardViewComponent } from './tracking-form-dashboard-view.component';
import { TrackingFormViewModule } from "src/app/components/psychotherapy/tracking/tracking-form-view/tracking-form-view.module";
import { PatientCardItemModule } from 'src/app/components/psychotherapy/patient/patient-card-item/patient-card-item.module';

@NgModule({

  declarations: [
    TrackingFormDashboardViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    NgSelectModule,
    CommonModule,
    TrackingFormViewModule,
    PatientCardItemModule
  ],

  exports: [
    TrackingFormDashboardViewComponent
  ]
})

export class TrackingFormDashboardViewModule { }        
        