services:
  angular-app:
    build: .
    ports:
      - "4200:80"
    container_name: angular-nginx
    restart: unless-stopped
    environment:
      - BACKEND_HOST=192.168.68.200
    networks:
      - default

networks:
  default:
    name: pm-net
    external: true