//File generated by vaweei CLI
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';

import  { AssignTaskModalViewComponent } from 'src/app/components/psychotherapy/tasks/task-dashboard-view/assign_task-modal-view/assign_task-modal-view.component';

import { PSYCHOTHERAPY } from 'src/app/utils/setup/routes.enum';

//SERVICE
import { HeaderService } from 'src/app/services/header.service';
import { BackendService } from 'src/app/services/backend.service';
import { UtilService } from 'src/app/services/util.service';

//MODELS
import { Patient } from 'src/app/models/patient.model';
import {SelectionModel} from '@angular/cdk/collections';
import {MatTableDataSource} from '@angular/material/table';

@Component({
  selector: 'app-patients_to_assign-list-view',
  templateUrl: './patients_to_assign-list-view.component.html',
  styleUrls: ['./patients_to_assign-list-view.component.scss']
})
export class PatientsToAssignListViewComponent implements OnInit {

  displayedColumns = ['image', 'first_name', 'phone_number', 'email', 'option'];
  dataSource = new MatTableDataSource<Patient>([]);

  $headerAction!: Subscription;
  $advanceSearch!: Subscription;

  constructor(
    private router : Router,
    private headerService : HeaderService,
    private backendService : BackendService,
    private utilService: UtilService,
    public dialog: MatDialog
    ) {}

  ngAfterViewInit(): void {

  }

  ngOnInit(): void {
    this.getAll();
  }

  getAll(){
   this.backendService.getAll(PSYCHOTHERAPY.PATIENT,{}).subscribe({
     next: (v) => { this.dataSource.data = v },
     error: (e) => console.error(e),
     complete: () => console.info('complete')
   });
  }

  // show(hobbies_interest_data:Hobbies_Interest){
  //   this.router.navigate(['main','catalogs','hobbies-interest','form',hobbies_interest_data.id]);
  // }

  openDialog() {
    const dialogRef = this.dialog.open(
      AssignTaskModalViewComponent,
      {
        height: '50%',
        width: '600px',
      }
      );

    dialogRef.afterClosed().subscribe(result => {
      console.log(`Dialog result: ${result}`);
    });
  }

}
    