//File generated by vaweei CLI
import { Component, OnInit, Output, EventEmitter, ViewChild, ElementRef, HostListener, OnDestroy, Input, AfterViewInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { GENERAL } from 'src/app/utils/setup/routes.enum';

//SERVICES
import { BackendService } from 'src/app/services/backend.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';
import {MatAccordion} from '@angular/material/expansion';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

//MODELS
import { MODELS } from 'src/app/utils/setup/model.setup';
import { Model } from 'src/app/models/vw-model.model';

@Component({
  selector: 'app-clinical_history-show-view',
  templateUrl: './clinical_history-show-view.component.html',
  styleUrls: ['./clinical_history-show-view.component.scss']
})
export class ClinicalHistoryShowViewComponent implements OnInit, OnDestroy, AfterViewInit {

  model : Model;


  record:any = {
    patient:{full_name:""},
    reason_consultation: {},
    nonverbal_language: {},
    hobbies_interest_list: {},
    personal_characteristics: {},
    therapy_objectives: {},
    approach: {}
  }

  area1 : any[] = []
  area2 : any[] = []
  area3 : any[] = []
  area4 : any[] = []

  displayedColumns = ['emotion','conduct','functionality','color'];

  $headerAction!: Subscription;

  @ViewChild(MatAccordion) accordion!: MatAccordion;

  private _clinical_history_data: any[] = [];   
  @Input()
  set clinical_history_data(value: any) { 
    this._clinical_history_data = value;
    if(value){
      this.buildData(value)
    }
  }  
  get clinical_history_data(): any { return this._clinical_history_data}

  isEmpty = false;

  //Report
  _id = ""
  medical_history_report_id = ""
  report_created = false;

  constructor(
    private backendService: BackendService,
    private headerService: HeaderService,
    private utilService: UtilService,
    private route: ActivatedRoute,
    private router : Router
  ) {
    this.model = MODELS.find(model => model.name == 'clinical-history')!;
    if(this.route.snapshot.paramMap.get('id')){
      this._id = this.route.snapshot.paramMap.get('id')!;
      this.clinical_noteById(this.route.snapshot.paramMap.get('id'));
    }
  }

  ngOnDestroy(): void {
    this.$headerAction.unsubscribe();
  }

  ngAfterViewInit(): void {
    this.$headerAction = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'edit':
          this.edit();
          break;
        case 'handle_generate_report':
          this.handle_generate_report();
          break;
        default:
          break;
      }
    });
  }

  ngOnInit() {
    this.headerService.setHeader({model: this.model, type:'show'});
    this.utilService.set({name:'clinical-history', type:'show'});
    if(this.clinical_history_data){
      this.buildData(this.clinical_history_data);
    }
  }

  buildData(data: any){
    this.record = data; this.setAreas(data);
  }

  clinical_noteById(id:any){
    if(id){
     this.backendService.getOneById(GENERAL.CLINICAL_HISTORY_PSYCHOTHERAPY,id).subscribe({
       next: (v) => {
        console.log("DATA");
        console.log(v);
        this.buildData(v);
        if(v){
          this.isEmpty = true
        }
      },
       error: (e) => console.error(e),
       complete: () => console.info('complete')
     });
    }
  }

  setAreas(data:any){
    data.support_network?.support_network_list.forEach((item: any) => {      
      switch (item.area) {
        case "1":
          this.area1.push(item)
          break;
        case "2":
          this.area2.push(item)
          break;
        case "3":
          this.area3.push(item)
          break;
        case "4":
          this.area4.push(item)
          break;
        default:
          break;
      }
    });
  }

  edit(){
    this.router.navigate(['catalogs','hobbies-interest','update',this.route.snapshot.paramMap.get('hobbies-interest_id')]);
  }

  viewEmotion(data:any){
    console.log(data)
  }

  handle_generate_report(){
    if (this.report_created) {
      this.router.navigate(['main','clinical-history','neuro-psychology','report-show',this.medical_history_report_id]);
    }else{
      this.router.navigate(['main','clinical-history','neuro-psychology','report-form',this._id]);
    }
  }
}
    