//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { ColorCircleModule } from 'ngx-color/circle';

import { NgSelectModule } from '@ng-select/ng-select';

import { ClinicalNoteFormDashboardViewComponent } from './clinical_note-form-dashboard-view.component';
import { ClinicalNoteFormViewComponent } from "src/app/components/clinical_history/clinical_note/clinical_note-form-view/clinical_note-form-view.component";
import { PatientCardItemModule } from 'src/app/components/psychotherapy/patient/patient-card-item/patient-card-item.module';

@NgModule({

  declarations: [
    ClinicalNoteFormDashboardViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    NgSelectModule,
    CommonModule,
    ClinicalNoteFormViewComponent,
    PatientCardItemModule
  ],

  exports: [
    ClinicalNoteFormDashboardViewComponent
  ]
})

export class ClinicalNoteFormDashboardViewModule { }        
        