//File generated by vaweei CLI
import { Component, OnInit, Output, EventEmitter, ViewChild, ElementRef, HostListener, OnDestroy, Input, AfterViewInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';

//SERVICES
import { HobbiesInterestService } from 'src/app/services/catalogs/hobbies_interest.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';

import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-hobbies_interest-show-form-view',
  templateUrl: './hobbies_interest-show-form-view.component.html',
  styleUrls: ['./hobbies_interest-show-form-view.component.scss']
})
export class Hobbies_InterestShowFormViewComponent implements OnInit, OnDestroy, AfterViewInit {

  record = {
    id: '', 
    code: '', name: '', 
  };

  $headerAction!: Subscription;

  constructor(
    private hobbiesInterestService: HobbiesInterestService,
    private headerService: HeaderService,
    private utilService: UtilService,
    private route: ActivatedRoute,
    private router : Router
  ) {}

  ngOnDestroy(): void {
    this.$headerAction.unsubscribe();
  }

  ngAfterViewInit(): void {
    this.$headerAction = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'edit':
          this.edit();
          break;
      
        default:
          break;
      }
    });

    this.utilService.set({name:'hobbies_interest', type:'show'});
  }

  ngOnInit() {
    this.headerService.setHeader({name:'hobbies_interest',type:'show'});
    if(this.route.snapshot.paramMap.get('hobbies-interest_id')){
      this.getHobbies_InterestById(this.route.snapshot.paramMap.get('hobbies-interest_id'));
    }
  }

  getHobbies_InterestById(id:any){
    if(id){
     this.hobbiesInterestService.getHobbiesInterestById(id).subscribe({
       next: (v) => { this.record = v[0] },
       error: (e) => console.error(e),
       complete: () => console.info('complete')
     });
    }
  }

  edit(){
    this.router.navigate(['catalogs','hobbies-interest','update',this.route.snapshot.paramMap.get('hobbies-interest_id')]);
  }

}
    