//File generated by vaweei CLI
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { PSYCHOTHERAPY } from 'src/app/utils/setup/routes.enum';

//SERVICE
import { TaskService } from 'src/app/services/psychotherapy/task.service';
import { HeaderService } from 'src/app/services/header.service';
import { BackendService } from 'src/app/services/backend.service';
import { UtilService } from 'src/app/services/util.service';

//MODELS
import { Patient } from 'src/app/models/patient.model';
import {SelectionModel} from '@angular/cdk/collections';
import {MatTableDataSource} from '@angular/material/table';

@Component({
  selector: 'app-task_template-list-view',
  templateUrl: './task_template-list-view.component.html',
  styleUrls: ['./task_template-list-view.component.scss']
})
export class TaskTemplateListViewComponent implements OnInit {

  displayedColumns = ['code', 'name', 'description', 'option'];
  dataSource = new MatTableDataSource<Patient>([]);

  $headerAction!: Subscription;
  $advanceSearch!: Subscription;

  constructor(
    private router : Router,
    private headerService : HeaderService,
    private backendService : BackendService,
    private utilService: UtilService,
    private taskService: TaskService
    ) {}

  ngAfterViewInit(): void {

  }

  ngOnInit(): void {
    this.getAllTaskTemplates();
  }

  getAll(){
   this.backendService.getAll(PSYCHOTHERAPY.PATIENT,{}).subscribe({
     next: (v) => { this.dataSource.data = v },
     error: (e) => console.error(e),
     complete: () => console.info('complete')
   });
  }

  getAllTaskTemplates(){
    this.taskService.getTaskTemplateList().subscribe({
      next: (v) => { this.dataSource.data = v },
      error: (e) => console.error(e),
      complete: () => console.info('complete')
    });
  }

  // show(hobbies_interest_data:Hobbies_Interest){
  //   this.router.navigate(['main','catalogs','hobbies-interest','form',hobbies_interest_data.id]);
  // }

}
    