//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { PruebaUpdateFormViewComponent } from './prueba-update-form-view.component';

@NgModule({

  declarations: [
    PruebaUpdateFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    CommonModule,
  ],

  exports: [
    PruebaUpdateFormViewComponent
  ]
})

export class PruebaUpdateFormViewModule { }      
        