//File generated by vaweei CLI
import { Component, OnInit, Output, EventEmitter, ViewChild, ElementRef, HostListener, OnDestroy, Input, AfterViewInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { CLINICAL_HISTORY } from 'src/app/utils/setup/routes.enum';

//SERVICES
import { BackendService } from 'src/app/services/backend.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';

//models
import { MODELS } from 'src/app/utils/setup/model.setup';
import { Model } from 'src/app/models/vw-model.model';

import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-clinical_note-show-form-view',
  templateUrl: './clinical_note-show-form-view.component.html',
  styleUrls: ['./clinical_note-show-form-view.component.scss']
})
export class ClinicalNoteShowFormViewComponent implements OnInit, OnDestroy, AfterViewInit {

  model : Model;

  record = {
    id: 0,
    session_approach: '',
    clinical_progress: '',
    session_objective: '',
    state_of_mind: '',
    conducts_and_non_verbal_languages: '',
    observations: ''
  };

  isModal = false

  $headerAction!: Subscription;

  constructor(
    private backendService: BackendService,
    private headerService: HeaderService,
    private utilService: UtilService,
    private route: ActivatedRoute,
    private router : Router
  ) {
    this.model = MODELS.find(model => model.name == 'clinical_note')!;
  }

  ngOnDestroy(): void {
    if(!this.isModal){
      this.$headerAction.unsubscribe();
    }
  }

  ngAfterViewInit(): void {
    if(!this.isModal){
      this.$headerAction = this.headerService.getOutAction().subscribe(data => {
        switch (data.action) {
          case 'edit':
            this.edit();
            break;
        
          default:
            break;
        }
      });
    }

  }

  ngOnInit() {
    this.headerService.setHeader({model: this.model, type:'show'});
    this.utilService.set({name:'clinical_note', type:'show'});
    if(this.route.snapshot.paramMap.get('clinical_note_id')){
      this.clinicalNoteById(this.route.snapshot.paramMap.get('clinical_note_id'));
    }else{
      this.isModal = true
    }
  }

  clinicalNoteById(id:any){
    if(id){
     this.backendService.getOneById(CLINICAL_HISTORY.CLINICAL_NOTE,id).subscribe({
       next: (v) => { this.record = v; console.log(v);
       },
       error: (e) => console.error(e),
       complete: () => console.info('complete')
     });
    }
  }

  edit(){
    this.router.navigate(['main','clinical-history','clinical_note','update',this.route.snapshot.paramMap.get('clinical_note_id')]);
  }

}

