//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { Hobbies_InterestUpdateFormViewComponent } from './hobbies_interest-update-form-view.component';

@NgModule({

  declarations: [
    Hobbies_InterestUpdateFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    CommonModule,
  ],

  exports: [
    Hobbies_InterestUpdateFormViewComponent
  ]
})

export class Hobbies_InterestUpdateFormViewModule { }      
        