//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { TrackingUpdateFormViewComponent } from './tracking-update-form-view.component';

@NgModule({

  declarations: [
    TrackingUpdateFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    CommonModule,
  ],

  exports: [
    TrackingUpdateFormViewComponent
  ]
})

export class TrackingUpdateFormViewModule { }      
        