//File generated by vaweei CLI
import { Component, OnInit, Output, EventEmitter, ViewChild, ElementRef, HostListener, OnDestroy, Input, AfterViewInit } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { PSYCHOTHERAPY } from 'src/app/utils/setup/routes.enum';

//SERVICES
import { BackendService } from 'src/app/services/backend.service';
import { HeaderService } from 'src/app/services/header.service';
import { UtilService } from 'src/app/services/util.service';

import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-tracking-show-form-view',
  templateUrl: './tracking-show-form-view.component.html',
  styleUrls: ['./tracking-show-form-view.component.scss']
})
export class TrackingShowFormViewComponent implements OnInit, OnDestroy, AfterViewInit {

  record = {
    id: '',
    session_approach: '',
    clinical_progress: '',
    session_objective: '',
    state_of_mind: '',
    conducts_and_non_verbal_languages: '',
    observations: ''
  };

  $headerAction!: Subscription;

  constructor(
    private backendService: BackendService,
    private headerService: HeaderService,
    private utilService: UtilService,
    private route: ActivatedRoute,
    private router : Router
  ) {}

  ngOnDestroy(): void {
    this.$headerAction.unsubscribe();
  }

  ngAfterViewInit(): void {
    this.$headerAction = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'edit':
          this.edit();
          break;
      
        default:
          break;
      }
    });

    this.utilService.set({name:'tracking', type:'show'});
  }

  ngOnInit() {
    this.headerService.setHeader({name:'tracking',type:'show'});
    console.log('here prron');
    
    if(this.route.snapshot.paramMap.get('tracking_id')){
      this.trackingById(this.route.snapshot.paramMap.get('tracking_id'));
    }
  }

  trackingById(id:any){
    if(id){
     this.backendService.getOneById(PSYCHOTHERAPY.TRACKING_BY_ID,id).subscribe({
       next: (v) => { this.record = v},
       error: (e) => console.error(e),
       complete: () => console.info('complete')
     });
    }
  }

  edit(){
    this.router.navigate(['catalogs','hobbies-interest','update',this.route.snapshot.paramMap.get('hobbies-interest_id')]);
  }

}
    