//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { ClinicalNoteUpdateFormViewComponent } from './clinical_note-update-form-view.component';

@NgModule({

  declarations: [
    ClinicalNoteUpdateFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    CommonModule,
  ],

  exports: [
    ClinicalNoteUpdateFormViewComponent
  ]
})

export class ClinicalNoteUpdateFormViewModule { }      
        