//File generated by vaweei CLI
import { Component, OnInit, Output, EventEmitter, ViewChild, ElementRef, HostListener, OnDestroy, Input, AfterViewInit } from '@angular/core';
import { UntypedFormGroup, UntypedFormControl, Validators, UntypedFormBuilder } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router'; 

//SERVICES
import { HeaderService } from 'src/app/services/header.service';
import { HobbiesInterestService } from 'src/app/services/catalogs/hobbies_interest.service';
import { UtilService } from 'src/app/services/util.service';

import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-clinical_note-update-form-view',
  templateUrl: './clinical_note-update-form-view.component.html',
  styleUrls: ['./clinical_note-update-form-view.component.scss']
})
export class ClinicalNoteUpdateFormViewComponent implements OnInit, OnDestroy, AfterViewInit {

  @ViewChild('firstInput', { static: false }) firstInput!: ElementRef;
  formGroup: UntypedFormGroup;
  @Input() modalConfigParent: any;
  @Input() nameForm: String = '';

  $headerAction!: Subscription;

  constructor(
    private headerService: HeaderService,
    private hobbiesInterestService: HobbiesInterestService,
    private utilService: UtilService,
    private router : Router,
    private route: ActivatedRoute,
    private fb: UntypedFormBuilder,
  ) {
    this.setFocus();
    this.formGroup = this.fb.group({
      id: new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      code: new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
      name: new UntypedFormControl(null, [Validators.required, Validators.maxLength(250)]),
    });
  }

  ngAfterViewInit(): void {
    this.$headerAction = this.headerService.getOutAction().subscribe(data => {
      switch (data.action) {
        case 'update':
          this.update();
          break;

        case 'cancel':
          this.cancel();
          break;

        default:
          break;
      }
    });
    this.utilService.set({name:'hobbies_interest', type:'update'});
  }

  ngOnInit() {
    this.headerService.setHeader({name:'hobbies_interest',type:'edit'});
    this.formGroup.statusChanges
      .pipe(
        filter(() => this.formGroup.valid))
      .subscribe(() => this.onFormValid());

    this.formGroup.statusChanges
      .pipe(
        filter(() => this.formGroup.invalid))
      .subscribe(() => this.onFormInvalid());

    if(this.route.snapshot.paramMap.get('hobbies-interest_id')){
      this.getHobbies_InterestById(this.route.snapshot.paramMap.get('hobbies-interest_id'));
    }
  }

  get paForm() { return this.formGroup.controls }
  
  ngOnDestroy() {
    this.$headerAction.unsubscribe();
  }

  onFormValid() {
    this.headerService.sendInAction({action:'update', type: 'ready'});
  }

  onFormInvalid() {
    this.headerService.sendInAction({action:'update', type: 'not-ready'});
  }

  private setFocus() {
    setTimeout(() => this.firstInput.nativeElement !== undefined ? this.firstInput.nativeElement.focus() : '');
  }

  changeToUppercase(formName:string) {
    if(formName){
      const value = this.formGroup.get(formName)!.value;
      if (value) {
        this.formGroup.get(formName)!.setValue(value.toUpperCase());
      }
    }
  }

  update(){
    this.hobbiesInterestService.updateHobbiesInterest(this.formGroup.value).subscribe({
     next: (v) => { console.log(v); },
     error: (e) => console.error(e),
     complete: () => this.router.navigate(['catalogs','hobbies-interest','table'])
    })
  }

  getHobbies_InterestById(id:any){
    if(id){
     this.hobbiesInterestService.getHobbiesInterestById(id).subscribe({
       next: (v) => { this.setHobbies_Interest(v[0]) },
       error: (e) => console.error(e),
       complete: () => console.info('complete')
     });
    }
  }

  setHobbies_Interest(record:any){
    this.formGroup.get('id')!.setValue(record.id);
    this.formGroup.get('code')!.setValue(record.code);
    this.formGroup.get('name')!.setValue(record.name);
  }

  cancel(){
    this.router.navigate(['catalogs','hobbies-interest','form',this.route.snapshot.paramMap.get('hobbies-interest_id')]);
  }
}
    