//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { ColorCircleModule } from 'ngx-color/circle';

import { Hobbies_InterestFormViewComponent } from './hobbies_interest-form-view.component';

@NgModule({

  declarations: [
    Hobbies_InterestFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    CommonModule
  ],

  exports: [
    Hobbies_InterestFormViewComponent
  ]
})

export class Hobbies_InterestFormViewModule { }        
        