//File generated by vaweei CLI
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { ColorCircleModule } from 'ngx-color/circle';

import { PruebaFormViewComponent } from './prueba-form-view.component';

@NgModule({

  declarations: [
    PruebaFormViewComponent,
  ],

  entryComponents: [
  ],

  providers: [
  ],

  imports: [
    ReactiveFormsModule,
    FormsModule,
    CommonModule
  ],

  exports: [
    PruebaFormViewComponent
  ]
})

export class PruebaFormViewModule { }        
        